export { IdentityBadge } from './IdentityBadge'
export type { IdentityBadgeProps } from './IdentityBadge'
export { ProfileIdentities } from './ProfileIdentities'
export type { ProfileIdentitiesProps, BoundDid } from './ProfileIdentities'
export { VerifiedBadge } from './VerifiedBadge'
export type { VerifiedBadgeProps, VerificationStatus } from './VerifiedBadge'
